{{- if .Values.api.ingress.enabled -}}
{{- $fullName := include "mlrun.api.fullname" . -}}
{{- $svcPort := .Values.api.service.port -}}
{{- $ingressPath := .Values.dashboard.ingress.path }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mlrun.api.labels" . | nindent 4 }}
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.api.ingress.tls }}
  tls:
  {{- range .Values.api.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.api.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: {{ $ingressPath }}
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
  {{- end }}
{{- end }}
